fixtures:
  forge_modules:
    stdlib: "puppetlabs/stdlib"
    concat: "puppetlabs/concat"
    apt: "puppetlabs/apt"
    inifile: "puppetlabs/inifile"
    zypprepo: "darin/zypprepo"
  symlinks:
    icingaweb2: "#{source_dir}"
